os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "6.9.5"
sudo: false
cache:
  directories:
    - monitora-client/node_modules
    - monitora-server/node_modules
env:
  global:
    - NODE_VERSION=6.9.5
before_install:
    - cd monitora-client
    - npm install -g create-react-app
install:
  - npm install
script:
  - npm test
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
